export const timelineData = [
  {
    date: "1950 - 1970",
    mainText: "The initial dream of a thinking machine.",
    graphData: [
      { label: "Unreliable", data: [0, 5, 8, 10, 12] },
      { label: "Reliable", data: [0, 2, 3, 5, 6] },
      { label: "Sentient", data: [0, 0, 0, 1, 1] },
    ],
    computeValue: 10,
    stats: [
      { value: "0%", label: "Approval" },
      { value: "$0B/yr", label: "Revenue" },
      { value: "$0B", label: "Valuation" },
      { value: "0%", label: "Importance" },
      { value: "$0B/yr", label: "Datacenters" },
      { value: "1960", label: "Timeline" },
    ],
    timelineIcons: ["🧠", "🧪", "⚙️", "📚", "🤔", "💡", "💻", "🤖", "🚀"],
  },
  {
    date: "1974 - 1980",
    mainText: "The first AI winter hits the industry hard.",
    graphData: [
      { label: "Unreliable", data: [12, 10, 8, 6, 5] },
      { label: "Reliable", data: [6, 5, 4, 3, 2] },
      { label: "Sentient", data: [1, 1, 0, 0, 0] },
    ],
    computeValue: 5,
    stats: [
      { value: "-25%", label: "Approval" },
      { value: "$0B/yr", label: "Revenue" },
      { value: "$0B", label: "Valuation" },
      { value: "0%", label: "Importance" },
      { value: "$0B/yr", label: "Datacenters" },
      { value: "1975", label: "Timeline" },
    ],
    timelineIcons: ["🥶", "📉", "💔", "❄️", "💤", "🚫", "💻", "🤖", "🚀"],
  },
  {
    date: "1980 - 1990",
    mainText: "The rise of Expert Systems brings new hope.",
    graphData: [
      { label: "Unreliable", data: [5, 15, 20, 25, 30] },
      { label: "Reliable", data: [2, 10, 15, 20, 25] },
      { label: "Sentient", data: [0, 0, 0, 0, 0] },
    ],
    computeValue: 20,
    stats: [
      { value: "50%", label: "Approval" },
      { value: "$10M/yr", label: "Revenue" },
      { value: "$50M", label: "Valuation" },
      { value: "5%", label: "Importance" },
      { value: "$1M/yr", label: "Datacenters" },
      { value: "1985", label: "Timeline" },
    ],
    timelineIcons: ["💡", "📈", "🧑‍🔬", "🧠", "🛠️", "💻", "🤖", "🚀", "🛸"],
  },
  {
    date: "2010 - 2020",
    mainText: "The Deep Learning revolution begins.",
    graphData: [
      { label: "Unreliable", data: [30, 45, 60, 75, 80] },
      { label: "Reliable", data: [25, 40, 55, 70, 75] },
      { label: "Sentient", data: [0, 0, 0, 1, 2] },
    ],
    computeValue: 60,
    stats: [
      { value: "75%", label: "Approval" },
      { value: "$10B/yr", label: "Revenue" },
      { value: "$500B", label: "Valuation" },
      { value: "25%", label: "Importance" },
      { value: "$50B/yr", label: "Datacenters" },
      { value: "2025", label: "Timeline" },
    ],
    timelineIcons: ["💡", "📈", "🧑‍🔬", "🧠", "🛠️", "💻", "🤖", "🚀", "🛸"],
  },
  {
    date: "2020 - Present",
    mainText: "Generative AI takes the world by storm.",
    graphData: [
      { label: "Unreliable", data: [80, 85, 90, 95, 100] },
      { label: "Reliable", data: [75, 80, 85, 90, 95] },
      { label: "Sentient", data: [2, 5, 10, 15, 25] },
    ],
    computeValue: 85,
    stats: [
      { value: "90%", label: "Approval" },
      { value: "$100B/yr", label: "Revenue" },
      { value: "$5T", label: "Valuation" },
      { value: "90%", label: "Importance" },
      { value: "$200B/yr", label: "Datacenters" },
      { value: "2030", label: "Timeline" },
    ],
    timelineIcons: ["🤖", "🚀", "🛸", "🌌", "🌠", "✨", "🌟", "🤩", "🤯"],
  },
];
